#!/bin/bash

set +e
exec 2> /dev/null # remove on debug

install_vr_platform_config()
{

    vrConfigFolder="/var/lib/vr-config/"

    if [ ! -d "$vrConfigFolder" ]; then
        mkdir "$vrConfigFolder"
    fi

    boardID=`fw_printenv board_id | sed -n "s/^board_id=//p"`
    case $boardID in
       "3D"|"40"|"41"|"42"|"52")  # Onyx board_ids
           cp /usr/sbin/onyx-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "3E"|"43"|"44"|"45"|"51")  # Quartz board_ids
           cp /usr/sbin/quartz-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "46"|"47"|"48")  # Ruby board_ids
           cp /usr/sbin/ruby-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "49"|"4A"|"4B"|"4C"|"4D"|"4E"|"4F")  # Titanite board_ids
          cp /usr/sbin/titanite-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "61"|"64")  # Sunstone board_ids
          cp /usr/sbin/sunstone-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "63")  # Cinnabar board_ids
          cp /usr/sbin/cinnabar-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "59"|"62"|"65")  # Shale board_ids
          cp /usr/sbin/shale-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "66" | "6E" | "6F") #Chalupa board_ids
          cp /usr/sbin/chalupa-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "67") #huambo board_ids
          cp /usr/sbin/huambo-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "68" | "70" | "71") #galena board_ids
          cp /usr/sbin/galena-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "69") #recluse board_ids
          cp /usr/sbin/recluse-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "6A" | "72" | "73") #purico board_ids
          cp /usr/sbin/purico-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "6B" | "74" | "75") #volcano board_ids
          cp /usr/sbin/volcano-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "5C" | "5D" | "5E" | "6C" | "6D" |"5F" | "60" ) #sh5 board_ids
          cp /usr/sbin/sh5-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "80" | "81" | "86" | "88" | "89" | "8B" | "8C" | "8D" | "9E" ) #Congo board_ids
          cp /usr/sbin/congo-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "82" | "83" | "87" | "8A" | "B0") #Morocco board_ids
          cp /usr/sbin/morocco-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "84") #kenya board_ids
          cp /usr/sbin/kenya-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "85") #nigeria board_ids
          cp /usr/sbin/nigeria-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "8E")
          cp /usr/sbin/ghana-vr.json "$vrConfigFolder/platform-vr.json"
      ;;
       "9F" | "A0" | "A1" | "AE" | "AF" | "B8" | "B9" | "BA")
          #Eagle and SLT Board IDs
          cp /usr/sbin/eagle-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "A2" | "A3" | "A4" | "A5" | "A6" | "A7" | "A8" | "A9" | "AA" | "AB" | "AC" | "AD")
          # hornbill and Duck Board IDs
          cp /usr/sbin/hornbill-vr.json "$vrConfigFolder/platform-vr.json"
      ;;
      "B1" | "B2" | "B3" | "B4") #falcon Board ID
          cp /usr/sbin/falcon-vr.json "$vrConfigFolder/platform-vr.json"
       ;;
       "B5" | "B6" | "B7") #seagull board_ids
          cp /usr/sbin/seagull-vr.json "$vrConfigFolder/platform-vr.json"
       esac

}

# all arguments are function names. invoke directly
if [ ! -z "$1" ] ; then
    $@
fi
